server:
  port: 8081
nha:
  services:
    nha-student-enrolment-service:
      baseUri: ${nha.host.url}:9091
      contextPath: /enrolment-service
spring:
  cloud:
    gateway:
      routes:
        - id: enrolments_client_routing
          uri: forward:/
          predicates:
            - Method=GET
            - Path=/enrolments/**
        - id: get_tajweed_enrolments_list
          uri: ${nha.services.nha-student-enrolment-service.baseUri}
          predicates:
            - Method=GET
            - Path=/api/enrolment/tajweed
          filters:
            - PrefixPath=${nha.services.nha-student-enrolment-service.contextPath}