name: Dependency update build
on:
  push:
    branches:
      - 'dependabot/**'
env:
  NODE_VERSION: '14.x'
jobs:
  build_and_deploy:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build application
        run: |
          rm package-lock.json
          npm install
          npm run coverage